import React,{Component,useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,Menu,X,Sun,Moon,Plus,Check,CalendarDays,Bookmark,MapPin,User,Info,ExternalLink,ChevronRight,DoorOpen,RefreshCw,Download,Share2,AlertTriangle,Clock3,Linkedin}from'lucide-react';import fallback from'./data/schedule.json';import'./style.css';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'],BATCHES=[['23','07','7th Semester'],['24','05','5th Semester'],['25','03','3rd Semester'],['26','01','1st Semester']],PROGRAMS={BBA:'Bachelor of Business Administration',AF:'BS Accounting & Finance',BSBA:'BS Business Analytics',FT:'BS Financial Technology'};
const clean=(s='')=>String(s).toLowerCase().replace(/[^a-z0-9]/g,''),safe={get(k,d){try{let v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}},today=()=>{try{let d=new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'Asia/Karachi'}).format(new Date());return DAYS.includes(d)?d:'All'}catch{return'All'}},to24=(display,fallback='')=>{let m=String(display).match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!m)return fallback;let h=Number(m[1])%12+(m[3].toUpperCase()==='PM'?12:0);return`${String(h).padStart(2,'0')}:${m[2]}`},mins=t=>{let m=String(t).match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):NaN},fmt=n=>`${Math.floor(n/60)%12||12}:${String(n%60).padStart(2,'0')} ${n<720?'AM':'PM'}`;
function sectionTokens(raw=''){let parts=String(raw).replace(/\s/g,'').toUpperCase().split('/'),out=[],base='';for(let p of parts){if(/^(BBA|AF|BSBA|BA|FT|BSFT)\d/.test(p)){p=p.replace(/^BA(?=\d)/,'BSBA').replace(/^BSFT/,'FT');out.push(p);base=p.replace(/[A-Z]\d*$/,'')}else if(base&&/^[A-Z]\d*$/.test(p))out.push(base+p)}return out}
function meta(token){let m=token.match(/^(BBA|AF|BSBA|FT)(\d+)([A-Z])(\d?)$/);if(!m)return null;return{degree:m[1],semester:m[2],repeat:!m[2].startsWith('0'),main:m[3],sub:m[4]?m[3]+m[4]:''}}
const key=x=>[x.day,x.start24,x.end24||'',x.room,x.code,x.title,x.section,x.type].map(clean).join('|');
class Boundary extends Component{constructor(p){super(p);this.state={bad:false}}static getDerivedStateFromError(){return{bad:true}}render(){return this.state.bad?<div className="fatal"><AlertTriangle/><h1>Unable to open timetable</h1><p>Reload the app. Your saved timetable is still stored on this device.</p><button onClick={()=>location.reload()}>Reload</button></div>:this.props.children}}
function App(){const[prefs,setPrefs]=useState(()=>safe.get('fsmPrefsV2',{version:2,batch:'',degree:'',main:'',sub:'',saved:[],manual:[],theme:'dark',profileActive:true})),[browse,setBrowse]=useState(()=>({batch:prefs.batch,degree:prefs.degree,main:prefs.main,sub:prefs.sub})),[data,setData]=useState(fallback),[sync,setSync]=useState({state:'loading',at:null,count:fallback.entries.length}),[page,setPage]=useState('timetable'),[drawer,setDrawer]=useState(false),[query,setQuery]=useState(''),[day,setDay]=useState(today()),[install,setInstall]=useState(null),[showUpdate,setShowUpdate]=useState(()=>!safe.get('fsmScheduleRevisionAug21Seen',false));
 useEffect(()=>{document.documentElement.dataset.theme=prefs.theme;safe.set('fsmPrefsV2',prefs)},[prefs]);useEffect(()=>{let h=e=>{e.preventDefault();setInstall(e)};addEventListener('beforeinstallprompt',h);refresh();return()=>removeEventListener('beforeinstallprompt',h)},[]);
 async function refresh(){setSync(s=>({...s,state:'loading'}));let ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),10000);try{let r=await fetch('/api/schedule',{signal:ctl.signal,cache:'no-store'});if(!r.ok)throw Error();let d=await r.json();if(!d.entries||d.entries.length<500)throw Error();setData(d);let at=new Date().toISOString();setSync({state:'live',at,count:d.entries.length});safe.set('fsmLastSync',{at,count:d.entries.length})}catch{let last=safe.get('fsmLastSync',null);setSync({state:'fallback',at:last?.at||null,count:fallback.entries.length})}finally{clearTimeout(timer)}}
 const entries=useMemo(()=>{let seen=new Set;return data.entries.map(x=>({...x,start24:to24(x.start,x.start24),end24:to24(x.end,x.end24||inferEnd(x.end))})).filter(x=>{let k=key(x);if(seen.has(k))return false;seen.add(k);return true})},[data]);
 useEffect(()=>{if(prefs.saved.length)return;let old=safe.get('savedKeys',[]);if(old.length)setPrefs(p=>({...p,saved:[...new Set(old)]}))},[]);
 const allMeta=useMemo(()=>entries.flatMap(x=>sectionTokens(x.section).map(meta).filter(Boolean)),[entries]);const semesters=BATCHES.filter(b=>allMeta.some(m=>m.semester===b[1]));const mainOptions=[...new Set(allMeta.filter(m=>m.semester===semesterOf(browse.batch)&&m.degree===browse.degree&&!m.repeat).map(m=>m.main))].sort();const repeats=[...new Set(allMeta.filter(m=>m.degree===browse.degree&&m.repeat).map(m=>`${m.semester}${m.main}`))].sort();const subOptions=[...new Set(allMeta.filter(m=>m.semester===semesterOf(browse.batch)&&m.degree===browse.degree&&m.main===browse.main&&m.sub).map(m=>m.sub))].sort();
 const profileRows=useMemo(()=>entries.filter(x=>matchesProfile(x,browse)),[entries,browse]),searched=profileRows.filter(x=>!query||clean([x.code,x.title,x.section,x.room,x.instructor].join(' ')).includes(clean(query))),visible=searched.filter(x=>day==='All'||x.day===day),savedRows=entries.filter(x=>prefs.saved.includes(key(x))),savedVisible=savedRows.filter(x=>day==='All'||x.day===day),clashKeys=new Set();
 const profileKeys=profileRows.map(key),allProfileSaved=profileKeys.length>0&&profileKeys.every(k=>prefs.saved.includes(k));
 useEffect(()=>{if(!prefs.batch||!prefs.degree||!prefs.main||prefs.profileActive===false)return;let current=entries.filter(x=>matchesProfile(x,prefs)).map(key),missing=current.filter(k=>!prefs.saved.includes(k));if(missing.length)setPrefs(p=>({...p,profileActive:true,saved:[...new Set([...p.saved,...missing])]}))},[entries,prefs.batch,prefs.degree,prefs.main,prefs.sub,prefs.profileActive]);
 const saveProfile=()=>setPrefs(p=>{let selected=new Set(profileKeys),next=allProfileSaved?p.saved.filter(k=>!selected.has(k)):[...new Set([...p.saved,...profileKeys])];return{...p,...browse,profileActive:!allProfileSaved,saved:next}}),toggle=x=>setPrefs(p=>({...p,saved:p.saved.includes(key(x))?p.saved.filter(k=>k!==key(x)):[...p.saved,key(x)]})),go=p=>{setPage(p);setDrawer(false);setDay(today());scrollTo({top:0,behavior:'smooth'})};
 const copyText=async()=>{let text=makeText(savedRows,prefs);try{await navigator.clipboard.writeText(text);alert('Timetable text copied')}catch{let box=document.createElement('textarea');box.value=text;box.style.position='fixed';box.style.opacity='0';document.body.appendChild(box);box.select();document.execCommand('copy');box.remove();alert('Timetable text copied')}};const exportText=async()=>{let text=makeText(savedRows,prefs);try{if(navigator.share)await navigator.share({title:'FSM Timetable',text});else await copyText()}catch{}};const exportImage=()=>makeImage(savedRows,prefs);
 return (
  <>
   <header>
    <button className="round" onClick={()=>setDrawer(true)}><Menu/></button>
    <button className="brand" onClick={()=>go('timetable')}><span>FSM</span><div><b>Timetable</b><small>Fall 2026 · Islamabad</small></div></button>
    <button className="round" onClick={()=>setPrefs(p=>({...p,theme:p.theme==='dark'?'light':'dark'}))}>{prefs.theme==='dark'?<Sun/>:<Moon/>}</button>
   </header>
   <main>
    {(page==='timetable'||page==='saved') ? (
     <>
      <Hero saved={page==='saved'} count={(page==='saved'?savedVisible:visible).length}/>
      {page==='timetable' && (
       <>
        <div className="filters v5">
         <label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Course, teacher, room…"/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</label>
         <select value={browse.batch} onChange={e=>setBrowse({batch:e.target.value,degree:'',main:'',sub:''})}><option value="">Select batch</option>{semesters.map(b=><option value={b[0]} key={b[0]}>Batch {b[0]} · {b[2]}</option>)}</select>
         <select value={browse.degree} disabled={!browse.batch} onChange={e=>setBrowse(b=>({...b,degree:e.target.value,main:'',sub:''}))}><option value="">Select degree</option>{Object.entries(PROGRAMS).map(([k,v])=><option value={k} key={k}>{v} ({k})</option>)}</select>
         <select value={browse.main} disabled={!browse.degree} onChange={e=>setBrowse(b=>({...b,main:e.target.value,sub:''}))}><option value="">Select section</option>{mainOptions.map(x=><option key={x}>{x}</option>)}{repeats.map(x=><option value={`repeat:${x}`} key={x}>{x} · Repeating course</option>)}</select>
         {subOptions.length>0&&<select value={browse.sub} onChange={e=>setBrowse(b=>({...b,sub:e.target.value}))}><option value="">Lab subgroup not assigned</option>{subOptions.map(x=><option key={x}>{x}</option>)}</select>}
        </div>
        {browse.main&&<div className="profileAction"><div><b>{profileLabel(browse)}</b><span>{profileRows.length} classes found</span></div><button className={allProfileSaved?'done':''} onClick={saveProfile}>{allProfileSaved?<Check/>:<Bookmark/>}{allProfileSaved?'Remove this timetable':'Use as my timetable'}</button></div>}
       </>
      )}
      <DayTabs day={day} setDay={setDay}/>
      {page==='saved'&&<ShareBar image={exportImage} text={exportText} copy={copyText}/>}
      <Schedule rows={page==='saved'?savedVisible:visible} saved={prefs.saved} toggle={toggle} clashKeys={clashKeys} day={day} savedPage={page==='saved'}/>
     </>
    ) : page==='rooms' ? <FreeRooms entries={entries}/> : <About install={install} trigger={async()=>{if(install){install.prompt();await install.userChoice;setInstall(null)}}}/>} 
   </main>
   <Bottom page={page} saved={prefs.saved.length} go={go} open={()=>setDrawer(true)}/>
   {drawer&&<Drawer close={()=>setDrawer(false)} go={go} sync={sync} refresh={refresh}/>} 
   {showUpdate&&<UpdateNotice close={()=>{safe.set('fsmScheduleRevisionAug21Seen',true);setShowUpdate(false)}}/>}
  </>
 )
}

function UpdateNotice({close}){return <div className="updateOverlay" role="dialog" aria-modal="true" aria-labelledby="updateTitle"><section className="updateNotice"><div className="updateIcon"><Check/></div><p>SCHEDULE UPDATED</p><h2 id="updateTitle">The revised Fall 2026 timetable is now available.</h2><span>The app now reads every recognized class and section entry from the latest official timetable.</span><ul><li>Revised class venues and schedule entries</li><li>Missing section classes are added to saved timetables automatically</li><li>Teacher details remain linked with the official Course Plan</li></ul><small>Your previously selected timetable remains saved. Please review today’s classes and venues once.</small><button onClick={close}>View updated timetable</button></section></div>}

function inferEnd(e=''){let m=e.match(/(\d+):(\d+)\s*(AM|PM)/i);if(!m)return'';let h=+m[1]%12+(m[3].toUpperCase()==='PM'?12:0);return`${String(h).padStart(2,'0')}:${m[2]}`}
const semesterOf=b=>BATCHES.find(x=>x[0]===b)?.[1]||'';
function matchesProfile(x,p){if(!p.batch||!p.degree||!p.main)return true;let ms=sectionTokens(x.section).map(meta).filter(Boolean);if(String(p.main).startsWith('repeat:')){let v=p.main.slice(7);return ms.some(m=>m.degree===p.degree&&m.repeat&&`${m.semester}${m.main}`===v)}let sem=semesterOf(p.batch);return ms.some(m=>m.degree===p.degree&&m.semester===sem&&m.main===p.main&&(!m.sub||!p.sub||m.sub===p.sub))}
function profileLabel(p){return`Batch ${p.batch} · ${p.degree} · ${String(p.main).replace('repeat:','Repeat ')}`+(p.sub?` · ${p.sub}`:'')}
function Hero({saved,count}){return <section className="hero"><div><p>FAST SCHOOL OF MANAGEMENT</p><h1>{saved?'Your timetable.':'Find your classes.'}</h1><span>{saved?'Today appears first. Switch days or export anytime.':'Choose batch, degree and section—or search directly.'}</span></div><aside><strong>{count}</strong><small>visible classes</small></aside></section>}
function DayTabs({day,setDay}){return <div className="dayTabs"><button className={day==='All'?'active':''} onClick={()=>setDay('All')}>All</button>{DAYS.map(d=><button className={day===d?'active':''} onClick={()=>setDay(d)} key={d}>{d.slice(0,3)}{d===today()&&<i>Today</i>}</button>)}</div>}
function Schedule({rows,saved,toggle,clashKeys,day,savedPage}){if(!rows.length)return <div className="empty"><CalendarDays/><h2>{savedPage&&day!=='All'?`No classes on ${day}`:'No matching classes'}</h2><p>{savedPage&&day!=='All'?'This is an off or reserved day for your saved timetable.':'Adjust the filters or search.'}</p></div>;return <div className="week">{DAYS.map(d=>{let list=rows.filter(x=>x.day===d).sort((a,b)=>mins(a.start24)-mins(b.start24)||mins(a.end24)-mins(b.end24)||String(a.title).localeCompare(String(b.title)));if(!list.length)return null;return <section className="day" key={d}><div className="dayhead"><h2>{d}</h2><span>{list.length} classes</span></div><div className="cards">{list.map(x=><article className={clashKeys.has(key(x))?'clash':''} key={key(x)}><i className="bar"/><div className="time"><b>{x.start}</b><small>to {x.end}</small><em>{duration(x)}</em></div><div className="details"><div><span className={x.type==='Lab'?'lab':''}>{x.type}</span>{x.code&&<span>{x.code}</span>}{clashKeys.has(key(x))&&<span className="clashTag">Clash</span>}</div><h3>{x.title}</h3><p><b>{x.section}</b><span><MapPin/>{x.room}</span><span className="teacher"><User/>{x.instructor||'TBA'}</span></p></div><button className={'save '+(saved.includes(key(x))?'done':'')} onClick={()=>toggle(x)}>{saved.includes(key(x))?<Check/>:<Plus/>}<span>{saved.includes(key(x))?'Saved':'Save'}</span></button></article>)}</div></section>})}</div>}
function duration(x){let n=mins(x.end24)-mins(x.start24);if(n<=0)return'';return`${Math.floor(n/60)?Math.floor(n/60)+' hr ':''}${n%60?n%60+' min':''}`.trim()}
function ShareBar({image,text,copy}){return <div className="shareBar"><button onClick={image}><Download/>Export image</button><button onClick={copy}><Bookmark/>Copy timetable text</button><button onClick={text}><Share2/>Share text</button></div>}
function ordered(rows){return [...rows].sort((a,b)=>DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||mins(a.start24)-mins(b.start24)||mins(a.end24)-mins(b.end24)||String(a.title).localeCompare(String(b.title)))}
function makeText(rows,p){let sorted=ordered(rows);return[`FSM Timetable · ${profileLabel(p)} · Fall 2026`,...DAYS.flatMap(d=>{let a=sorted.filter(x=>x.day===d);return a.length?[`\n${d}`,...a.map(x=>`${x.start}–${x.end} — ${x.code} ${x.title}\nRoom: ${x.room} · Teacher: ${x.instructor||'TBA'}`)]:[]})].join('\n')}
function makeImage(rows,p){let w=1600,pad=70,rowH=88,groups=DAYS.map(d=>[d,ordered(rows.filter(x=>x.day===d))]).filter(x=>x[1].length),h=150+groups.reduce((n,g)=>n+55+g[1].length*rowH,0)+80,c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d');x.fillStyle='#f5f8f9';x.fillRect(0,0,w,h);x.fillStyle='#102129';x.font='700 44px Arial';x.fillText('FSM Timetable · Fall 2026',pad,65);x.font='22px Arial';x.fillStyle='#526b76';x.fillText(profileLabel(p),pad,105);let y=150;for(let[d,a]of groups){x.fillStyle='#0f4c5c';x.fillRect(pad,y,w-pad*2,42);x.fillStyle='white';x.font='700 22px Arial';x.fillText(d,pad+18,y+28);y+=55;for(let r of a){x.fillStyle='white';x.fillRect(pad,y,w-pad*2,rowH-8);x.fillStyle='#0e7f86';x.fillRect(pad,y,7,rowH-8);x.fillStyle='#102129';x.font='700 20px Arial';x.fillText(`${r.start}–${r.end}`,pad+25,y+29);x.font='700 21px Arial';x.fillText(`${r.code||''} ${r.title}`,pad+275,y+29);x.font='17px Arial';x.fillStyle='#526b76';x.fillText(`${r.section} · ${r.room} · ${r.instructor||'TBA'} · ${duration(r)}`,pad+275,y+59);y+=rowH}}let a=document.createElement('a');a.download='fsm-timetable.png';a.href=c.toDataURL('image/png');a.click()}
function FreeRooms({entries}){const[d,setD]=useState(today()==='All'?'Monday':today()),[time,setTime]=useState('08:30');let rooms=[...new Set(entries.map(x=>x.room))].sort(),busy=new Set(entries.filter(x=>x.day===d&&x.start24===time).map(x=>x.room));return <><section className="hero"><div><p>ROOM FINDER</p><h1>Free rooms.</h1><span>Inferred from the currently synced FSM timetable.</span></div></section><div className="roomFilters"><select value={d} onChange={e=>setD(e.target.value)}>{DAYS.map(x=><option key={x}>{x}</option>)}</select><select value={time} onChange={e=>setTime(e.target.value)}>{['08:30','10:00','11:30','13:00','14:25','15:50'].map(x=><option key={x}>{x}</option>)}</select></div><div className="roomGrid">{rooms.filter(r=>!busy.has(r)).map(r=><article key={r}><DoorOpen/><b>{r}</b><span>Available</span></article>)}</div><p className="note">Special events and last-minute reservations may not be reflected.</p></>}
function About({install,trigger}){return <section className="about"><p>FAST · SIMPLE · RELIABLE</p><h1>A timetable built for daily FSM life.</h1><span>Choose your section once, see today’s classes, detect overlaps and share a clean schedule.</span><div className="installCard"><Clock3/><div><h2>Install on your phone</h2><p>Android Chrome: menu → Install app. iPhone Safari: Share → Add to Home Screen.</p>{install&&<button onClick={trigger}>Install now</button>}</div></div><a href="https://www.linkedin.com/in/syed-ali-hadi" target="_blank"><Linkedin/>Connect with Syed Ali Hadi<ExternalLink/></a></section>}
function Bottom({page,saved,go,open}){return <nav><button className={page==='timetable'?'active':''} onClick={()=>go('timetable')}><CalendarDays/>Timetable</button><button className={page==='saved'?'active':''} onClick={()=>go('saved')}><span><Bookmark/>{saved>0&&<i>{saved}</i>}</span>Saved</button><button onClick={open}><Menu/>More</button></nav>}
function Drawer({close,go,sync,refresh}){return <><button className="scrim" onClick={close}/><section className="drawer"><div><h2>Menu</h2><button className="round" onClick={close}><X/></button></div>{[['timetable',CalendarDays,'Timetable'],['saved',Bookmark,'My timetable'],['rooms',DoorOpen,'Free rooms'],['about',Info,'About & install']].map(([p,I,t])=><button onClick={()=>go(p)} key={p}><span><I/></span><b>{t}</b><ChevronRight/></button>)}<div className={'syncCard '+sync.state}><b>{sync.state==='live'?'Live timetable':sync.state==='loading'?'Checking timetable…':'Saved snapshot'}</b><span>{sync.at?`Last synced ${new Date(sync.at).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}`:'No successful live sync yet'}</span><span>{sync.count} schedule entries · FSM</span><button onClick={refresh}><RefreshCw/>Refresh timetable</button></div></section></>}
createRoot(document.getElementById('root')).render(<Boundary><App/></Boundary>);
