const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
function csvRows(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}
const sec=/^(?:BS)?(?:BBA|BA|AF|FT)\s*-?\s*\d{1,2}[A-Z](?:\d)?(?:\s*\/\s*(?:(?:BS)?(?:BBA|BA|AF|FT))?\s*\d{0,2}[A-Z](?:\d)?)?$/i;
const isSec=s=>sec.test((s||'').replace(/\s+/g,''));
function sectionKeys(s){s=s.toUpperCase().replace(/[\s-]/g,'');if(!s.includes('/'))return[s];const[a,b]=s.split('/'),m=a.match(/^(.*\d)([A-Z]\d?)$/);return /^[A-Z]\d?$/.test(b)&&m?[a,m[1]+b]:[a,b]}
function time12(t){let[h,m]=t.split(':').map(Number);return`${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`}
function explicit(raw){const p=[...raw.matchAll(/(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})/g)];if(!p.length)return null;const cv=x=>{let[h,m]=x.split(':').map(Number);if(h>=1&&h<=5)h+=12;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`};return[cv(p.at(-1)[1]),cv(p.at(-1)[2])]}
function parse(text){const rows=csvRows(text),slots=[[3,'08:30','09:50'],[12,'10:00','11:20'],[21,'11:30','12:50'],[30,'13:00','14:20'],[39,'14:25','15:45'],[48,'15:50','17:10']];let day='',type='Class';const entries=[];rows.forEach((source,ri)=>{const row=[...source,...Array(Math.max(0,56-source.length)).fill('')];if(DAYS.includes(row[0]?.trim()))day=row[0].trim();if(/^labs?/i.test(row[1]?.trim()))type='Lab';else if(/^classes?/i.test(row[1]?.trim()))type='Class';let room=row[2]?.trim();if(!day||!room||room==='Room'||room==='Labs')return;const anchors=row.map((v,i)=>[i,(v||'').trim()]).filter(([i,v])=>i>=3&&v);anchors.forEach(([sc,section],idx)=>{if(!isSec(section))return;let j=idx-1;while(j>=0&&isSec(anchors[j][1]))j--;if(j<0)return;const[tc,raw]=anchors[j];if(/^(cs|ms|jumma prayer)$/i.test(raw)||/^seminar/i.test(raw))return;const slot=slots.filter(x=>x[0]<=tc).at(-1)||slots[0];let st=slot[1],en=slot[2];const et=explicit(raw);if(et)[st,en]=et;let stripped=raw.replace(/\s*\(?\d{1,2}:\d{2}\s*[-–]\s*\d{1,2}:\d{2}\)?/g,'').trim(),m=stripped.match(/^([A-Z]{2})\s?(\d{4})\s*/);entries.push({id:`${day.slice(0,2)}-${ri+1}-${tc+1}-${sc+1}`,day,start:time12(st),end:time12(en),start24:st,end24:en,room:room.replace(/\s+/g,' ').replace('A--','A-').replace('A- ','A-'),type,code:m?m[1]+m[2]:'',title:m?stripped.slice(m[0].length).trim():stripped,section:section.replace(/\s+/g,''),sectionKeys:sectionKeys(section),instructor:''})})});const all=[...new Set(entries.flatMap(x=>x.sectionKeys))];const programs={'BBA':all.filter(x=>x.startsWith('BBA')).sort(),'BS Business Analytics':all.filter(x=>x.startsWith('BSBA')).sort(),'BS Accounting & Finance':all.filter(x=>x.startsWith('AF')).sort(),'BS Financial Technology':all.filter(x=>x.startsWith('FT')).sort()};return{meta:{entryCount:entries.length,source:'Live Google Sheet CSV',updated:new Date().toISOString()},programs,entries}}
export default async function handler(req,res){const id='1AnFQQhv9lu4grESE2ypbDG7E1QOPGgGCRiejem5ocPw',urls=[`https://docs.google.com/spreadsheets/d/${id}/gviz/tq?tqx=out:csv&gid=0`,`https://docs.google.com/spreadsheets/d/${id}/export?format=csv&gid=0`];for(const url of urls){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'}});if(r.ok){const text=await r.text();if(text.includes('FAST School of Management')){const data=parse(text);if(data.entries.length>600){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');return res.status(200).json(data)}}}}catch{}}return res.status(503).json({error:'Live sheet unavailable'})}
